name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: check availability
      run: |
        ./bpf-core-availability.sh
    - name: make
      run: |
        make
