name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        runner:
          - ubuntu-20.04
          - ubuntu-18.04
    runs-on: ${{ matrix.runner }}
    steps:
    - uses: actions/checkout@v3
    - name: check availability
      run: |
        ./bpf-core-availability.sh
    - name: build
      run: |
        make
    - name: test
      run: |
        make test
